### ISSUE TITLE
Grouping is based on naming in stead of compose projects 

### ISSUE THREAD

**Issue by iamrgroot** [RickWong/Captain#17]
When you use `container_name` in the docker-compose, the grouping is broken.

Reproduction: create the following `docker-compose.yml` in a folder called `testdocker`

```yml
services:
  node-1:
    container_name: custom-node
    image: node
    command: tail -f /dev/null

  node-2:
    image: node
    command: tail -f /dev/null
```

Docker desktop groups them: 
<img width="520" alt="image" src="https://github.com/user-attachments/assets/3619591f-8cad-4f75-8329-6832ce251686">

Captain does not:
![image](https://github.com/user-attachments/assets/b39962d4-d63b-4d58-a501-1c517189bee1)
![image](https://github.com/user-attachments/assets/a08baf96-bee3-46bd-977e-b56bcd34f179)

Please let me know if you would like me to contribute a fix myself
